services:
  # Backend Service
  - type: web
    name: groot-2
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Auto-deploy from main branch
    branch: main
    rootDir: backend

  # Frontend Service  
  - type: web
    name: groot-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    # Auto-deploy from main branch
    branch: main
    rootDir: frontend
