services:
  # Backend Service
  - type: web
    name: groot-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://groot-frontend.onrender.com
    # Auto-deploy from main branch
    branch: main
    rootDir: backend

  # Frontend Service  
  - type: web
    name: groot-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://groot-backend.onrender.com
    # Auto-deploy from main branch
    branch: main
    rootDir: frontend
